### ISSUE TITLE
Crash when importing ics file exported from calendar-import-export

### ISSUE THREAD

**Issue by red-black-bonsai** [SufficientlySecure/calendar-import-export#94]
To migrate the local calendar from phone A to phone B, I created an export with CIE on phone A, copied the ics to phone B and tried importing. CIE, version 2.7, just closes/crashes.

Installing CIE version 2.6 from F-Droid store (after first uninstalling version 2.7) on phone B alleviates the problem. With it, I can import fine (even a file generated by 2.7 on phone A) :)

Potentially relevant log from import on phone B:

    03-24 18:49:14.269 22905 22934 E AndroidRuntime: FATAL EXCEPTION: Thread-3
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: Process: org.sufficientlysecure.ical, PID: 22905
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: java.lang.ExceptionInInitializerError
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: 	at net.fortuna.ical4j.util.Configurator.getProperty(Unknown Source:0)
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: 	at net.fortuna.ical4j.util.CompatibilityHints.<clinit>(Unknown Source:9)
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: 	at net.fortuna.ical4j.util.CompatibilityHints.setHintEnabled(Unknown Source:0)
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: 	at org.sufficientlysecure.ical.ui.MainActivity$LoadFile.setHint(Unknown Source:0)
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: 	at org.sufficientlysecure.ical.ui.MainActivity$LoadFile.run(Unknown Source:12)
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: 	at org.sufficientlysecure.ical.ui.dialogs.RunnableWithProgress$1.run(Unknown Source:2)
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: Caused by: org.apache.commons.logging.LogConfigurationException: java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.logging.impl.LogFactoryImpl" on path: DexPathList[[zip file "/data/app/~~F1kOHNBP-ITQYlfyjUJwlQ==/org.sufficientlysecure.ical-voKQx_iG8O0BI950MvAZ8w==/base.apk"],nativeLibraryDirectories=[/data/app/~~F1kOHNBP-ITQYlfyjUJwlQ==/org.sufficientlysecure.ical-voKQx_iG8O0BI950MvAZ8w==/lib/arm64, /system/lib64, /system_ext/lib64]] (Caused by java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.logging.impl.LogFactoryImpl" on path: DexPathList[[zip file "/data/app/~~F1kOHNBP-ITQYlfyjUJwlQ==/org.sufficientlysecure.ical-voKQx_iG8O0BI950MvAZ8w==/base.apk"],nativeLibraryDirectories=[/data/app/~~F1kOHNBP-ITQYlfyjUJwlQ==/org.sufficientlysecure.ical-voKQx_iG8O0BI950MvAZ8w==/lib/arm64, /system/lib64, /system_ext/lib64]])
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: 	at org.apache.commons.logging.LogFactory.createFactory(Unknown Source:459)
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: 	at org.apache.commons.logging.LogFactory$2.run(Unknown Source:4)
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: 	at java.security.AccessController.doPrivileged(AccessController.java:43)
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: 	at org.apache.commons.logging.LogFactory.newFactory(Unknown Source:5)
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: 	at org.apache.commons.logging.LogFactory.getFactory(Unknown Source:487)
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: 	at org.apache.commons.logging.LogFactory.getLog(Unknown Source:0)
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: 	at net.fortuna.ical4j.util.Configurator.<clinit>(Unknown Source:20)
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: 	... 7 more
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.logging.impl.LogFactoryImpl" on path: DexPathList[[zip file "/data/app/~~F1kOHNBP-ITQYlfyjUJwlQ==/org.sufficientlysecure.ical-voKQx_iG8O0BI950MvAZ8w==/base.apk"],nativeLibraryDirectories=[/data/app/~~F1kOHNBP-ITQYlfyjUJwlQ==/org.sufficientlysecure.ical-voKQx_iG8O0BI950MvAZ8w==/lib/arm64, /system/lib64, /system_ext/lib64]]
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: 	at org.apache.commons.logging.LogFactory.createFactory(Unknown Source:5)
    03-24 18:49:14.269 22905 22934 E AndroidRuntime: 	... 13 more
    03-24 18:49:14.276  1391 10670 W ActivityTaskManager:   Force finishing activity org.sufficientlysecure.ical/.ui.MainActivity

**Comment by thewholelifetolearn** [comment]
I encounter the same issue after updating to v2.7. The app crashed when opening a file. After uninstalling and reinstalling, the app opened but crashed when charging the ics file.
I'm on android 12.

**Comment by sail2themoon** [comment]
Hi, same crash for me with 2.7 - thank you very much, red-black-bonsai for telling us, that version 2.6, manually chosen in f-droid, is working fine, so it does for me.

**Comment by fhaftmann** [comment]
There is now a release 2.7.1 available at https://f-droid.org/en/packages/org.sufficientlysecure.ical/ – please check whether this resolves the issue you experience.

**Comment by thewholelifetolearn** [comment]
I have tried 2.7.1 version but it didn't change anything. It still crashes when opening a file. I had to return to 2.6.0

**Comment by skylarmt** [comment]
I'm having crashes on 2.7.2 still with importing calendar files.  I open the ICS from my email app and as soon as I press Load in this app it crashes.

**Comment by fhaftmann** [comment]
I can reproduce the error: it occurs during the static initialization of net.fortuna.ical4j.util.Configurator.

Applying the work-arodung suggest in https://stackoverflow.com/questions/60018008/android-apache-logger-crashes-for-no-reason-in-production-release-build helps, see https://github.com/SufficientlySecure/calendar-import-export/commit/1b3ab3807c2df81a76f63b84eca6a5db6635b782.

A new release is schedule, stay tuned.

**Comment by k-svn** [comment]
Unfortunately, version 2.7.4 is even worse than 2.7.2. In the last version the app crashed when selecting an ics import file. Now it already crashes when you just click on "import file"...

**Comment by kusalux** [comment]
Can confirm worse behavior - crash on "import file" with 2.7.4. With clean installed A12L (5.April 22 Patch) Rom.

**Comment by fhaftmann** [comment]
Unfortunately, I cannot reproduce the issue, using android emulator with Android 12.0 / API 31 / x86_64.

Since the crash is reported to happen when clicking »import file«, the exact content of the file should be irrelevant. There must be subtle differences with the setup.

Actually, there have been a lot of participants in this thread. Are there any among you who get along with 2.7.4? This could give important clues what goes wrong here.

**Comment by skylarmt** [comment]
> Android 12.0 / API 31 / x86_64

I'm running 2.7.4 from F-Droid. My device is Android 11 (LineageOS 18.1) with ARM64.

Here's my logcat when I press Import File:

```
E AndroidRuntime: java.lang.VerifyError: Verifier rejected class org.sufficientlysecure.ical.ui.MainActivity$CalendarSource:  
    java.net.URLConnection org.sufficientlysecure.ical.ui.MainActivity$CalendarSource.getConnection() failed to verify:  
    java.net.URLConnection org.sufficientlysecure.ical.ui.MainActivity$CalendarSource.getConnection():  
    [0x50] 'this' argument 'Precise Reference: org.apache.commons.codec.binary.Base64' not instance of  
    'Reference: org.apache.commons.codec.binary.BaseNCodec' (declaration of 'org.sufficientlysecure.ical.ui.MainActivity$CalendarSource' appears in base.apk)
E AndroidRuntime:        at org.sufficientlysecure.ical.ui.MainActivity$SearchForFiles.search(Unknown Source:53)
E AndroidRuntime:        at org.sufficientlysecure.ical.ui.MainActivity$SearchForFiles.search(Unknown Source:20)
E AndroidRuntime:        at org.sufficientlysecure.ical.ui.MainActivity$SearchForFiles.run(Unknown Source:27)
E AndroidRuntime:        at org.sufficientlysecure.ical.ui.dialogs.RunnableWithProgress$1.run(Unknown Source:2)
W ActivityTaskManager:   Force finishing activity org.sufficientlysecure.ical/.ui.MainActivity
```

**Comment by fhaftmann** [comment]
I cannot reproduce the behaviour, but the log clearly points to the line changed in https://github.com/SufficientlySecure/calendar-import-export/commit/a23e7326bba65fee44f61f3adb0555dce9fe8a9e

There are hints that the Android framework uses a fixed version of the Commons Codec library, cf. https://stackoverflow.com/questions/9126567/method-not-found-using-digestutils-in-android/29833101#29833101

Speculatively it is better to avoid to rely on inheritance here, maybe that plain static method call works better.

If this doesn't help either, I plan to go with https://github.com/ExCiteS/apache-commons-codec-shaded and include a whole clone of Commons Codec.

**Comment by k-svn** [comment]
Well done! Import with 2.7.5 works fine again! Thanks you 👍🏻

**Comment by skylarmt** [comment]
2.7.5 works for me too.
